/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InternalRouteImport } from './routes/_internal'
import { Route as ClientRouteImport } from './routes/client'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as InternalAuditRouteImport } from './routes/_internal/audit'
import { Route as InternalCommunicationsRouteImport } from './routes/_internal/communications'
import { Route as InternalDashboardRouteImport } from './routes/_internal/dashboard'
import { Route as InternalIntakeRouteImport } from './routes/_internal/intake'
import { Route as InternalPaymentsRouteImport } from './routes/_internal/payments'
import { Route as InternalTodayRouteImport } from './routes/_internal/today'
import { Route as ClientIndexRouteImport } from './routes/client/index'
import { Route as ClientCasesRouteImport } from './routes/client/cases'
import { Route as ClientConfirmationsRouteImport } from './routes/client/confirmations'
import { Route as ClientStatementsRouteImport } from './routes/client/statements'
import { Route as ClientUploadRouteImport } from './routes/client/upload'
import { Route as InternalCasesIndexRouteImport } from './routes/_internal/cases/index'
import { Route as InternalCasesIdRouteImport } from './routes/_internal/cases/$id'
import { Route as InternalClientsIndexRouteImport } from './routes/_internal/clients/index'
import { Route as InternalClientsNewRouteImport } from './routes/_internal/clients/new'
import { Route as InternalGstIndexRouteImport } from './routes/_internal/gst/index'
import { Route as InternalGstCaseIdRouteImport } from './routes/_internal/gst/$caseId'
import { Route as InternalMsmeIndexRouteImport } from './routes/_internal/msme/index'
import { Route as InternalMsmeCaseIdRouteImport } from './routes/_internal/msme/$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalRoute = InternalRouteImport.update({
  id: '/_internal',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalAuditRoute = InternalAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => InternalRoute,
} as any)
const InternalCommunicationsRoute = InternalCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => InternalRoute,
} as any)
const InternalDashboardRoute = InternalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => InternalRoute,
} as any)
const InternalIntakeRoute = InternalIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => InternalRoute,
} as any)
const InternalPaymentsRoute = InternalPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => InternalRoute,
} as any)
const InternalTodayRoute = InternalTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => InternalRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientCasesRoute = ClientCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => ClientRoute,
} as any)
const ClientConfirmationsRoute = ClientConfirmationsRouteImport.update({
  id: '/confirmations',
  path: '/confirmations',
  getParentRoute: () => ClientRoute,
} as any)
const ClientStatementsRoute = ClientStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => ClientRoute,
} as any)
const ClientUploadRoute = ClientUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ClientRoute,
} as any)
const InternalCasesIndexRoute = InternalCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => InternalRoute,
} as any)
const InternalCasesIdRoute = InternalCasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => InternalRoute,
} as any)
const InternalClientsIndexRoute = InternalClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => InternalRoute,
} as any)
const InternalClientsNewRoute = InternalClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => InternalRoute,
} as any)
const InternalGstIndexRoute = InternalGstIndexRouteImport.update({
  id: '/gst/',
  path: '/gst/',
  getParentRoute: () => InternalRoute,
} as any)
const InternalGstCaseIdRoute = InternalGstCaseIdRouteImport.update({
  id: '/gst/$caseId',
  path: '/gst/$caseId',
  getParentRoute: () => InternalRoute,
} as any)
const InternalMsmeIndexRoute = InternalMsmeIndexRouteImport.update({
  id: '/msme/',
  path: '/msme/',
  getParentRoute: () => InternalRoute,
} as any)
const InternalMsmeCaseIdRoute = InternalMsmeCaseIdRouteImport.update({
  id: '/msme/$caseId',
  path: '/msme/$caseId',
  getParentRoute: () => InternalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/audit': typeof InternalAuditRoute
  '/communications': typeof InternalCommunicationsRoute
  '/dashboard': typeof InternalDashboardRoute
  '/intake': typeof InternalIntakeRoute
  '/payments': typeof InternalPaymentsRoute
  '/today': typeof InternalTodayRoute
  '/client/cases': typeof ClientCasesRoute
  '/client/confirmations': typeof ClientConfirmationsRoute
  '/client/statements': typeof ClientStatementsRoute
  '/client/upload': typeof ClientUploadRoute
  '/client/': typeof ClientIndexRoute
  '/cases/$id': typeof InternalCasesIdRoute
  '/clients/new': typeof InternalClientsNewRoute
  '/gst/$caseId': typeof InternalGstCaseIdRoute
  '/msme/$caseId': typeof InternalMsmeCaseIdRoute
  '/cases/': typeof InternalCasesIndexRoute
  '/clients/': typeof InternalClientsIndexRoute
  '/gst/': typeof InternalGstIndexRoute
  '/msme/': typeof InternalMsmeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/audit': typeof InternalAuditRoute
  '/communications': typeof InternalCommunicationsRoute
  '/dashboard': typeof InternalDashboardRoute
  '/intake': typeof InternalIntakeRoute
  '/payments': typeof InternalPaymentsRoute
  '/today': typeof InternalTodayRoute
  '/client/cases': typeof ClientCasesRoute
  '/client/confirmations': typeof ClientConfirmationsRoute
  '/client/statements': typeof ClientStatementsRoute
  '/client/upload': typeof ClientUploadRoute
  '/client': typeof ClientIndexRoute
  '/cases/$id': typeof InternalCasesIdRoute
  '/clients/new': typeof InternalClientsNewRoute
  '/gst/$caseId': typeof InternalGstCaseIdRoute
  '/msme/$caseId': typeof InternalMsmeCaseIdRoute
  '/cases': typeof InternalCasesIndexRoute
  '/clients': typeof InternalClientsIndexRoute
  '/gst': typeof InternalGstIndexRoute
  '/msme': typeof InternalMsmeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_internal': typeof InternalRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_internal/audit': typeof InternalAuditRoute
  '/_internal/communications': typeof InternalCommunicationsRoute
  '/_internal/dashboard': typeof InternalDashboardRoute
  '/_internal/intake': typeof InternalIntakeRoute
  '/_internal/payments': typeof InternalPaymentsRoute
  '/_internal/today': typeof InternalTodayRoute
  '/client/cases': typeof ClientCasesRoute
  '/client/confirmations': typeof ClientConfirmationsRoute
  '/client/statements': typeof ClientStatementsRoute
  '/client/upload': typeof ClientUploadRoute
  '/client/': typeof ClientIndexRoute
  '/_internal/cases/$id': typeof InternalCasesIdRoute
  '/_internal/clients/new': typeof InternalClientsNewRoute
  '/_internal/gst/$caseId': typeof InternalGstCaseIdRoute
  '/_internal/msme/$caseId': typeof InternalMsmeCaseIdRoute
  '/_internal/cases/': typeof InternalCasesIndexRoute
  '/_internal/clients/': typeof InternalClientsIndexRoute
  '/_internal/gst/': typeof InternalGstIndexRoute
  '/_internal/msme/': typeof InternalMsmeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client'
    | '/sign-in'
    | '/audit'
    | '/communications'
    | '/dashboard'
    | '/intake'
    | '/payments'
    | '/today'
    | '/client/cases'
    | '/client/confirmations'
    | '/client/statements'
    | '/client/upload'
    | '/client/'
    | '/cases/$id'
    | '/clients/new'
    | '/gst/$caseId'
    | '/msme/$caseId'
    | '/cases/'
    | '/clients/'
    | '/gst/'
    | '/msme/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/audit'
    | '/communications'
    | '/dashboard'
    | '/intake'
    | '/payments'
    | '/today'
    | '/client/cases'
    | '/client/confirmations'
    | '/client/statements'
    | '/client/upload'
    | '/client'
    | '/cases/$id'
    | '/clients/new'
    | '/gst/$caseId'
    | '/msme/$caseId'
    | '/cases'
    | '/clients'
    | '/gst'
    | '/msme'
  id:
    | '__root__'
    | '/'
    | '/_internal'
    | '/client'
    | '/sign-in'
    | '/_internal/audit'
    | '/_internal/communications'
    | '/_internal/dashboard'
    | '/_internal/intake'
    | '/_internal/payments'
    | '/_internal/today'
    | '/client/cases'
    | '/client/confirmations'
    | '/client/statements'
    | '/client/upload'
    | '/client/'
    | '/_internal/cases/$id'
    | '/_internal/clients/new'
    | '/_internal/gst/$caseId'
    | '/_internal/msme/$caseId'
    | '/_internal/cases/'
    | '/_internal/clients/'
    | '/_internal/gst/'
    | '/_internal/msme/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InternalRoute: typeof InternalRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_internal': {
      id: '/_internal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof InternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_internal/audit': {
      id: '/_internal/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof InternalAuditRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/communications': {
      id: '/_internal/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof InternalCommunicationsRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/dashboard': {
      id: '/_internal/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof InternalDashboardRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/intake': {
      id: '/_internal/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof InternalIntakeRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/payments': {
      id: '/_internal/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof InternalPaymentsRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/today': {
      id: '/_internal/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof InternalTodayRouteImport
      parentRoute: typeof InternalRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/cases': {
      id: '/client/cases'
      path: '/cases'
      fullPath: '/client/cases'
      preLoaderRoute: typeof ClientCasesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/confirmations': {
      id: '/client/confirmations'
      path: '/confirmations'
      fullPath: '/client/confirmations'
      preLoaderRoute: typeof ClientConfirmationsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/statements': {
      id: '/client/statements'
      path: '/statements'
      fullPath: '/client/statements'
      preLoaderRoute: typeof ClientStatementsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/upload': {
      id: '/client/upload'
      path: '/upload'
      fullPath: '/client/upload'
      preLoaderRoute: typeof ClientUploadRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_internal/cases/': {
      id: '/_internal/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof InternalCasesIndexRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/cases/$id': {
      id: '/_internal/cases/$id'
      path: '/cases/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof InternalCasesIdRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/clients/': {
      id: '/_internal/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof InternalClientsIndexRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/clients/new': {
      id: '/_internal/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof InternalClientsNewRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/gst/': {
      id: '/_internal/gst/'
      path: '/gst'
      fullPath: '/gst/'
      preLoaderRoute: typeof InternalGstIndexRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/gst/$caseId': {
      id: '/_internal/gst/$caseId'
      path: '/gst/$caseId'
      fullPath: '/gst/$caseId'
      preLoaderRoute: typeof InternalGstCaseIdRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/msme/': {
      id: '/_internal/msme/'
      path: '/msme'
      fullPath: '/msme/'
      preLoaderRoute: typeof InternalMsmeIndexRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/msme/$caseId': {
      id: '/_internal/msme/$caseId'
      path: '/msme/$caseId'
      fullPath: '/msme/$caseId'
      preLoaderRoute: typeof InternalMsmeCaseIdRouteImport
      parentRoute: typeof InternalRoute
    }
  }
}

interface InternalRouteChildren {
  InternalAuditRoute: typeof InternalAuditRoute
  InternalCommunicationsRoute: typeof InternalCommunicationsRoute
  InternalDashboardRoute: typeof InternalDashboardRoute
  InternalIntakeRoute: typeof InternalIntakeRoute
  InternalPaymentsRoute: typeof InternalPaymentsRoute
  InternalTodayRoute: typeof InternalTodayRoute
  InternalCasesIdRoute: typeof InternalCasesIdRoute
  InternalClientsNewRoute: typeof InternalClientsNewRoute
  InternalGstCaseIdRoute: typeof InternalGstCaseIdRoute
  InternalMsmeCaseIdRoute: typeof InternalMsmeCaseIdRoute
  InternalCasesIndexRoute: typeof InternalCasesIndexRoute
  InternalClientsIndexRoute: typeof InternalClientsIndexRoute
  InternalGstIndexRoute: typeof InternalGstIndexRoute
  InternalMsmeIndexRoute: typeof InternalMsmeIndexRoute
}

const InternalRouteChildren: InternalRouteChildren = {
  InternalAuditRoute: InternalAuditRoute,
  InternalCommunicationsRoute: InternalCommunicationsRoute,
  InternalDashboardRoute: InternalDashboardRoute,
  InternalIntakeRoute: InternalIntakeRoute,
  InternalPaymentsRoute: InternalPaymentsRoute,
  InternalTodayRoute: InternalTodayRoute,
  InternalCasesIdRoute: InternalCasesIdRoute,
  InternalClientsNewRoute: InternalClientsNewRoute,
  InternalGstCaseIdRoute: InternalGstCaseIdRoute,
  InternalMsmeCaseIdRoute: InternalMsmeCaseIdRoute,
  InternalCasesIndexRoute: InternalCasesIndexRoute,
  InternalClientsIndexRoute: InternalClientsIndexRoute,
  InternalGstIndexRoute: InternalGstIndexRoute,
  InternalMsmeIndexRoute: InternalMsmeIndexRoute,
}

const InternalRouteWithChildren = InternalRoute._addFileChildren(
  InternalRouteChildren,
)

interface ClientRouteChildren {
  ClientCasesRoute: typeof ClientCasesRoute
  ClientConfirmationsRoute: typeof ClientConfirmationsRoute
  ClientStatementsRoute: typeof ClientStatementsRoute
  ClientUploadRoute: typeof ClientUploadRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientCasesRoute: ClientCasesRoute,
  ClientConfirmationsRoute: ClientConfirmationsRoute,
  ClientStatementsRoute: ClientStatementsRoute,
  ClientUploadRoute: ClientUploadRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InternalRoute: InternalRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
